# PHP project
language: php

# which versions of PHP to build with
php:
- 7.0

# set global environment variables
env:
  global:
    # make PROJECTNAME from vendor/project
    # this strips everything before the last /
    - PROJECTNAME=${TRAVIS_REPO_SLUG##*/}

# make sure we have the latest version of composer
before_install:
- composer self-update

# install dependencies
install:
- composer install

# no phpunit tests (yet)
script: true

# no email notifications
notifications:
  email: false

# before deployment make the zipfile to upload
before_deploy:
 # execute release prepare script
 - sh ./vendor/coldtrick/releases/scripts/travis/before_deploy.sh

# deployment settings
deploy:
  provider: releases
  api_key:
    secure: WzJvCaDr70gvGP4BMVLlAwu0KyCqSb/P7R7IyBLutuHf6l2sYnT3uCT5k+XX+lxNnKZ0TFXL+uHr4DeEEoThGcicLDQpY/S2gepy/dv+LN1Y1bndfxyP7QgbJOVxZ/2mHGMHDUO7Sw7KPyFcFRMu2czn1q7XdN6sfjFvllRo8bz2e9YaT5fIylcF2axkQY5mam/yhxUkmgpiyQvzzvG43Kzdwbjn2+GUCn1y0gg/rC4htZobbtj8fZnPOS3KZ0Q3OBHiyWDD4nKbVPXNsgxXZ2di+IZceZC90qdtr8tEmDrUvCINDVytDs8YooggUdEq6i4Rya4nVNhK4FJRvXHyGTdCTDAu0g363pro6HoQn6VlERpsR0ohC1LUM5mqyaUTMccKd8JV781/3snd44DJDsNbpL2b5SSRgTk9cE6O3KMNP7yLT+OIWyVwcyRTs0TuL7AHj7NYBB3+TeRrC3dFBHU1tUn4hHNWMzg9rO2DabCnpoX4QMjztOU3dp8yARVHBFgB2SERlaSr+NoeOKZHEE9zl/sffrEaWD8md8dKH/w/zQVX0RncYVfc/RlutJ7oO6bFDoPTQH2oWV9oFawekfloblqgtDscxzLO+4pihbQUpN3rtknVD04GDri8tFgaASkUcRt2ETs16aq0s9ubrYQCmlZSZ72asoCRutEaFxo=
  # name of the zip to upload
  file: ${PROJECTNAME}_$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    # only when a tag is created in GitHub
    tags: true
    all_branches: true

after_deploy:
 # execute release after script
 - sh ./vendor/coldtrick/releases/scripts/travis/after_deploy.sh
